In [1]:
x = [5,5,48,45,45,4135,2]

In [2]:
x.sort()

In [6]:
max(x),min(x),sum(x),type(x)

(4135, 2, 4285, list)

In [11]:
b= lambda y: y**4
b(5)

625

In [14]:
x = 0.1
while x<10:
    x += 1
    print(x)

1.1
2.1
3.1
4.1
5.1
6.1
7.1
8.1
9.1
10.1


In [15]:
a = 0
while a<30:
    a+=1
    if a% 2==0:
        print(a)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30


In [16]:
harfler = "abcdef"
for harf in harfler:
    print(harf)

a
b
c
d
e
f


In [17]:
for i in range(1,10):
               print(i)

1
2
3
4
5
6
7
8
9


In [25]:
for i in range(10):
               print(i+4)

4
5
6
7
8
9
10
11
12
13


In [26]:
import numpy as np

In [30]:
x = np.array([1,2,3,4])
x,type(x)

(array([1, 2, 3, 4]), numpy.ndarray)

In [34]:
x.max(),max(x),x.nonzero()

(4, 4, (array([0, 1, 2, 3], dtype=int64),))

In [43]:
np.zeros((3,4)),
np.ones((5,3)),

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),)

In [44]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [47]:
np.linspace(0,4,12)

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [48]:
np.random.rand(3,4)

array([[0.25361183, 0.26857386, 0.20229423, 0.45641002],
       [0.01176882, 0.48763361, 0.0207372 , 0.53374506],
       [0.6429188 , 0.55041724, 0.46470249, 0.38933751]])

In [51]:
np.eye(5)*10+5

array([[15.,  5.,  5.,  5.,  5.],
       [ 5., 15.,  5.,  5.,  5.],
       [ 5.,  5., 15.,  5.,  5.],
       [ 5.,  5.,  5., 15.,  5.],
       [ 5.,  5.,  5.,  5., 15.]])

In [60]:
c = np.random.randint(1,50,15)
c

array([20, 16, 15, 11,  9,  6, 36,  1, 11, 42, 49, 39, 46, 29,  9])

In [54]:
y = np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [64]:
c.max()+c.min(),c.argmax()

(50, 10)

In [67]:
a = np.arange(30)
a.shape = 2,-1,5
a.shape

(2, 3, 5)

In [68]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [71]:
b = np.arange(10)**2
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [72]:
b[4:6]

array([16, 25], dtype=int32)

In [74]:
b[4]=100

In [75]:
b[4]

100

In [76]:
b

array([  0,   1,   4,   9, 100,  25,  36,  49,  64,  81], dtype=int32)

In [78]:
for i in b:
    print(i+2)

2
3
6
11
102
27
38
51
66
83


In [100]:
y = np.random.random(16)

In [101]:
y

array([0.64456112, 0.88022091, 0.65477058, 0.82308338, 0.96011935,
       0.90265537, 0.58242395, 0.59662635, 0.07061789, 0.47588815,
       0.29185597, 0.32640296, 0.91625099, 0.64199485, 0.27613557,
       0.13743253])

In [102]:
y.reshape(4,4)

array([[0.64456112, 0.88022091, 0.65477058, 0.82308338],
       [0.96011935, 0.90265537, 0.58242395, 0.59662635],
       [0.07061789, 0.47588815, 0.29185597, 0.32640296],
       [0.91625099, 0.64199485, 0.27613557, 0.13743253]])

In [103]:
y.ravel()

array([0.64456112, 0.88022091, 0.65477058, 0.82308338, 0.96011935,
       0.90265537, 0.58242395, 0.59662635, 0.07061789, 0.47588815,
       0.29185597, 0.32640296, 0.91625099, 0.64199485, 0.27613557,
       0.13743253])

In [97]:
y

array([0.859701  , 0.24760748, 0.60359736, 0.27563211, 0.86779847,
       0.49858846, 0.98243697, 0.00434905, 0.96146704, 0.31600687,
       0.59686704, 0.1363674 , 0.47932895, 0.14439587, 0.53840813,
       0.87541642])

In [104]:
y[0:2]

array([0.64456112, 0.88022091])

In [105]:
y[:,3]

IndexError: too many indices for array