# NUMPY EGZERSİZLERİ

# Array oluşturma

#### Import numpy as np (Numpy ı yükleyin )

In [1]:
import numpy as np

### ([1,2,3,4,5]) elemanlarından oluşan bir array tanımlayın

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [3]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

### 0 lardan oluşan 4 satırlı 5 sütunlu bir array oluşturun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [5]:
b=np.zeros((4,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 7 lerden oluşan 3 satırlı  5 sütunlu bir array oluşturun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [6]:
b=np.ones((3,5))*7
b

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

### 10 dan başlayarak 70 e kadar 5 er artan bir array oluşturun ( arange( ) fonksiyonunu kullanın)

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [8]:
a = np.arange(10,70,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

### 0 ile 5 arasında 15 tane aynı uzaklıkta elemanı olan bir array oluşturun( linspace( ) fonksiyonunu kullanın)

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [16]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

### Normal dağılımda 3 satır 5 sütunlu bir array oluşturun ( random.randn( ) )

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [17]:
np.random.randn(3,5)

array([[-0.96523939, -0.39866939,  1.16956048, -0.53759076,  0.25935361],
       [-0.97700666,  0.34840283, -0.16836694,  0.93417642, -0.69622445],
       [ 0.12032059, -1.16109588,  2.03658066,  0.99668744,  0.68185063]])

### 5 elemanlı birim matris oluşturun ( eye( ) )

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [19]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### 0 dan 24 e kadar sayıların olduğu bir array oluşturun ve reshape() metodunu kullanarak 4 satır ve 6 sütunlu hale getirin.

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [15]:
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayıp en düşük ve en yüksek değerleri tespit edin.

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [20]:
b = np.random.rand(10)
print(b)
print(b.max())
print(b.min())

[0.89112231 0.74176309 0.13362715 0.87405214 0.84010186 0.80342317
 0.87029136 0.60911445 0.87007443 0.83186475]
0.8911223062088145
0.1336271530274442


# Numpy indeksleme ve iterasyon



### Rastgele 16 sayıdan oluşan ve 4 satır 4 sütunlu bir array oluşturun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [21]:
r = np.random.rand(16).reshape(4,4)
r

array([[0.02956211, 0.29713299, 0.79003916, 0.38119288],
       [0.11248911, 0.26547403, 0.71243626, 0.2889958 ],
       [0.81022789, 0.36066006, 0.10704943, 0.53929721],
       [0.19578583, 0.37675725, 0.07568719, 0.02737908]])

### 2.satır daki tüm elemanları çekin

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [26]:
r[3,3]

0.027379084337383452

### 4 üncü satır 4 üncü sütundaki sayıyı çekin

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

In [22]:
r[1:2,:]

0.68715134034939174

### 4 üncü sütundaki bütün elemanları çekin

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0.91218194],
       [ 0.15974578],
       [ 0.17761038],
       [ 0.68715134]])

### For döngüsünü kullanarak oluşturduğunuz 16 sayıdan oluşan array in sayılarını alt alta flat() metodunu kullanarak yazdırın

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

0.488802679735
0.168573650955
0.16996915822
0.912181942492
0.943398301456
0.113132394171
0.663649343748
0.159745777232
0.487685134439
0.597886756923
0.216674205666
0.177610382955
0.0979582874017
0.679986864771
0.825719779735
0.687151340349


# Numpy işlemler

### 0 ile 1 arasında Rastgele 4 sayıdan oluşan bir array oluşturun ve her sayıyı 5 ile çarpın

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([ 3.59596072,  2.88977277,  3.23761792,  2.07067878])

### Oluşturduğunuz array in sayılarının toplamını bulun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

9.2846101377415025

### Oluşturduğunuz array in standart sapmasını bulun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

1.4977659819850548

### Oluşturduğunuz array in varyansını bulun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

2.2433029367916557