In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
type(x)

numpy.ndarray

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones((4,5))*100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [7]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(10.1,50.5,5)

array([10.1, 15.1, 20.1, 25.1, 30.1, 35.1, 40.1, 45.1, 50.1])

In [15]:
lin = np.linspace(0,4,12)
lin

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [20]:
rast = np.random.rand(3,4)
rast

array([[0.64399947, 0.66069521, 0.12082829, 0.34495452],
       [0.37892431, 0.44511003, 0.38455934, 0.6104656 ],
       [0.4216931 , 0.25119622, 0.80086796, 0.38951014]])

In [22]:
n = np.random.rand(2,5)
n

array([[0.10652445, 0.86083155, 0.8444384 , 0.97834739, 0.3881695 ],
       [0.81827655, 0.21403371, 0.85090905, 0.17174564, 0.50624119]])

In [23]:
n = np.random.rand(2,5)*10
n


array([[2.40879451, 7.19270591, 6.95342595, 1.20993029, 5.8627122 ],
       [1.64565684, 5.95400929, 5.48617671, 6.84524812, 6.41431815]])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
c = np.random.randint(10,50,15)
c

array([35, 46, 15, 17, 36, 49, 38, 28, 38, 49, 29, 36, 31, 30, 48])

In [33]:
y= np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c.max()

49

In [38]:
c.min()

15

In [41]:
c.argmax()

5

In [40]:
c.argmin()

2

In [44]:
a = np.arange(50)
a.shape = 2,-1,5
a.shape

(2, 5, 5)

In [45]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])