In [10]:
import numpy as np
a = np.arange(10)**5
a

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049], dtype=int32)

In [18]:
a[3]

243

In [12]:
a[3:6]

array([ 243, 1024, 3125], dtype=int32)

In [13]:
for i in a:
    print(i*2)

0
2
64
486
2048
6250
15552
33614
65536
118098


In [14]:
y =np.random.random(16)

In [15]:
y

array([0.84737719, 0.70426517, 0.49617767, 0.28829418, 0.3330275 ,
       0.65566483, 0.05159893, 0.77968105, 0.76686704, 0.56230284,
       0.13946955, 0.59000858, 0.99614969, 0.42621277, 0.8145524 ,
       0.80473305])

In [17]:
y = y.reshape(4,4)
y

array([[0.84737719, 0.70426517, 0.49617767, 0.28829418],
       [0.3330275 , 0.65566483, 0.05159893, 0.77968105],
       [0.76686704, 0.56230284, 0.13946955, 0.59000858],
       [0.99614969, 0.42621277, 0.8145524 , 0.80473305]])

In [19]:
y.ravel()

array([0.84737719, 0.70426517, 0.49617767, 0.28829418, 0.3330275 ,
       0.65566483, 0.05159893, 0.77968105, 0.76686704, 0.56230284,
       0.13946955, 0.59000858, 0.99614969, 0.42621277, 0.8145524 ,
       0.80473305])

In [21]:
y[0:2,1]

array([0.70426517, 0.65566483])

In [23]:
y[:,3]

array([0.28829418, 0.77968105, 0.59000858, 0.80473305])

In [25]:
for satır in y:
    print(satır)

[0.84737719 0.70426517 0.49617767 0.28829418]
[0.3330275  0.65566483 0.05159893 0.77968105]
[0.76686704 0.56230284 0.13946955 0.59000858]
[0.99614969 0.42621277 0.8145524  0.80473305]


In [26]:
for satır in y.flat:
    print(satır)

0.8473771866525412
0.7042651696097499
0.49617767079614583
0.2882941761385204
0.333027500564395
0.6556648310241818
0.0515989310512287
0.7796810454151406
0.7668670412768831
0.5623028449083639
0.13946954733027084
0.590008575465529
0.9961496854491925
0.42621277112124023
0.8145524026302293
0.804733052538761


In [29]:
 for satır in np.ndenumerate(y):
        print(satır)

((0, 0), 0.8473771866525412)
((0, 1), 0.7042651696097499)
((0, 2), 0.49617767079614583)
((0, 3), 0.2882941761385204)
((1, 0), 0.333027500564395)
((1, 1), 0.6556648310241818)
((1, 2), 0.0515989310512287)
((1, 3), 0.7796810454151406)
((2, 0), 0.7668670412768831)
((2, 1), 0.5623028449083639)
((2, 2), 0.13946954733027084)
((2, 3), 0.590008575465529)
((3, 0), 0.9961496854491925)
((3, 1), 0.42621277112124023)
((3, 2), 0.8145524026302293)
((3, 3), 0.804733052538761)


In [33]:
a = np.array([2,3])
b = np.array([5,6])

In [34]:
np.hstack((a,b))

array([2, 3, 5, 6])

In [35]:
np.vstack((a,b))

array([[2, 3],
       [5, 6]])

In [39]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.concatenate((a,b.T),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])