In [3]:
import numpy as np

a=np.array([20,40,60,80])
a

array([20, 40, 60, 80])

In [4]:
b = np.arange(4)
b


array([0, 1, 2, 3])

In [5]:
c = a+b
c

array([20, 41, 62, 83])

In [6]:
a**2

array([ 400, 1600, 3600, 6400], dtype=int32)

In [7]:
a>50

array([False, False,  True,  True])

In [8]:
a +=10
a

array([30, 50, 70, 90])

In [9]:
x = np.random.random(15)
x

array([0.22893181, 0.74830804, 0.07866322, 0.67500576, 0.60394544,
       0.45592536, 0.72909358, 0.848373  , 0.47244826, 0.35846855,
       0.36096935, 0.28487302, 0.05149685, 0.36017959, 0.31424259])

In [10]:
x.max()

0.8483729987703857

In [11]:
x.min()

0.05149685032427964

In [12]:
x.sum()

6.570924429682414

In [13]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
b.sum(axis = 0)

array([15, 18, 21, 24, 27])

In [15]:
b.sum(axis = 1)

array([10, 35, 60])

In [16]:
b.max(axis = 0)

array([10, 11, 12, 13, 14])

In [17]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [18]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27]], dtype=int32)

In [19]:
k = np.random.random(15)
k

array([0.76946553, 0.92901931, 0.99015766, 0.5363366 , 0.17524149,
       0.40962223, 0.67955541, 0.08930505, 0.39560302, 0.72933489,
       0.80239995, 0.91395869, 0.6455488 , 0.17176882, 0.87762629])

In [20]:
k.mean()

0.6076629147699034

In [21]:
np.median(k)

0.6795554083510384

In [22]:
np.std(k)

0.2871403614872607

In [23]:
np.var(k)

0.08244958719503474

In [26]:
kopya = k.copy()

In [27]:
kopya

array([0.76946553, 0.92901931, 0.99015766, 0.5363366 , 0.17524149,
       0.40962223, 0.67955541, 0.08930505, 0.39560302, 0.72933489,
       0.80239995, 0.91395869, 0.6455488 , 0.17176882, 0.87762629])

In [29]:
şehir = np.array(["ankara","istanbul","bursa","izmir","ankara","bursa"])
np.unique(şehir)

array(['ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')